---
variables:
  GIT_STRATEGY: none
  PY_COLORS: "1"
stages:
  - deploy
deploy:
  image: registry.git.coop/webarch/containers/images/bookworm:20230605
  stage: deploy
  script:
    - whoami
    - pwd
    - mkdir ~/.ssh
    - chmod 600 ~/.ssh
    - cd ~/.ssh
    - git clone https://git.coop/webarch/webarch-ssh.git
    - echo "Include ~/.ssh/webarch-ssh/config" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - cd
    - pipx install mkdocs
    - pipx ensurepath
    - git clone https://git.coop/workers/docs.git
    - mkdocs build
    - rsync -av ./site docs@office.workers.coop:sites/mkdocs/
