---
variables:
  GIT_STRATEGY: none
  PATH: "${HOME}/.local/bin:${PATH}"
  PY_COLORS: "1"
before_script:
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - cd ~/.ssh
  - git clone https://git.coop/webarch/webarch-ssh.git
  - echo "Include ~/.ssh/webarch-ssh/config" > ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - pipx install mkdocs
  - pipx install pymarkdownlnt
  - pipx install yamllint
  - pipx ensurepath
  - cd
stages:
  - stage
  - live
stage:
  stage: stage
  image: registry.git.coop/webarch/containers/images/bookworm:20230605
  variables:
    SITE_NAME: STAGING DOCS
    SITE_URL: https://stage.docs.workers.coop/
  script:
    - git clone https://git.coop/workers/docs.git
    - cd docs
    - yamllint .
    - pymarkdownlnt scan .
    - mkdocs build
    - rsync -av ./site docs@office.workers.coop:sites/stage/
live:
  stage: live
  image: registry.git.coop/webarch/containers/images/bookworm:20230605
  variables:
    SITE_NAME: workers.coop docs
    SITE_URL: https://docs.workers.coop/
  script:
    - git clone https://git.coop/workers/docs.git
    - cd docs
    - mkdocs build
    - rsync -av ./site docs@office.workers.coop:sites/mkdocs/
  when: manual
after_script:
  - rm -rf /home/ansible/.ssh
...
