---
variables:
  GIT_STRATEGY: none
  PY_COLORS: "1"
before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir ~/.ssh
  - chmod 600 ~/.ssh
  - cd ~/.ssh
  - git clone https://git.coop/webarch/webarch-ssh.git
  - echo "Include ~/.ssh/webarch-ssh/config" > ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - cd
stages:
  - deploy
deploy:
  image: registry.git.coop/webarch/containers/images/bookworm:20230605
  stage: deploy
  script:
    - pipx install mkdocs
    - pipx ensurepath
    - git clone https://git.coop/workers/docs.git
    - mkdocs build
    - rsync -av ./site docs@office.workers.coop:sites/mkdocs/
