---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: YAML Lint
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.11
    hooks:
      - id: pymarkdown
        name: Markdown Lint
...
