---
site_name: !ENV [SITE_NAME, 'LOCAL DOCS']
site_url: !ENV [SITE_URL, 'http://127.0.0.1:8000/']
nav:
  - 'Home': index.md
  - 'Members':
      - 'Single Sign-On': 'members/sso.md'
  - 'Administrators':
      - 'Cal.com': 'admins/cal.md'
      - 'Discourse': 'admins/discourse.md'
      - 'Nextcloud': 'admins/nc.md'
      - 'WordPress/CiviCRM': 'admins/wp.md'
  - 'System Administrators':
      - 'DNS': 'sysadmins/dns.md'
      - 'Servers': 'sysadmins/servers.md'
theme: readthedocs
...
